version: '3.9'

services:
  psql_auth:
    image: postgres
    container_name: psql_auth
    environment:
      POSTGRES_USER: izydor
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bm_dev_auth
    ports:
      - 7777:5432
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data/
  inpost_api_auth:
    build:
      dockerfile: Dockerfile
      context: ./api
    working_dir: /app
    volumes:
      - ./api:/app
    container_name: inpost_api_auth
    ports:
      - 9900:9900
    restart: always
    network_mode: "host"
    depends_on:
      - psql_auth

volumes:
  postgres_data_auth: